spring:
  profiles:
    active:
      - dev
---
spring:
  application:
    name: config-test-dev
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  application:
    name: config-test-default
  profiles: beta
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  application:
    name: config-test-prod
  profiles: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
